baseURL = 'https://github.com/Seinichts/seinichts.github.io'
languageCode = 'en-us'
title = 'Zelong Blog'

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"


[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
    math = true
