#+hugo_base_dir: ~/orgblog/

* DONE Differentiation :math:
CLOSED: [2024-07-20 Sat 22:50]
:PROPERTIES:
:EXPORT_FILE_NAME: Differentiation
:END:

+ Normally, if without any statements, \( f \) is a real-valued continuous function on \( [a,b] \)

* Definition of differentiation
*Definition* For a function \(f\), defined on interval \([a,b]\). For \(x \in [a,b ]\)
$$\lim_{t \to x } \frac{f(t) - f(x)}{t - x} $$
is called the differentiate of f at x, denotes by \(f'(x)\).

Apparently, to let \(f'(x)\) exists, the function has to have left/right limit (or both) at the point \(x\). That is, differentiable implies the function \(f\) is also continuous at the point.


#+begin_quote
However, continuity does not imply the differentiability of \(f\) at x. If left limit at point \(x\) does not equal to the right limit, then \(f'(x)\) will have two different value for one point, which is not possible for a well-defined function.
#+end_quote

* Calculation
** Basic operations
First we have to define the most basic operation, that is \(+(-), \times, \div\)

*** Addition
\begin{align*}
(f + g)'(x) &= \lim_{t \to x} \frac{(f+g)(t) - (f+g)(x)}{t-x} \\
&= \lim_{ t \to x } \frac{f(t) - f(x) +g(t) - g(x)}{t - x} \\
&= f'(x) + g'(x)
\end{align*}

*** Multiplication
The idea is use 凑配法 to pairing up

\begin{align*}
fg'(x) &= \lim_{ t \to x } \frac{fg(t) - fg(x)}{t -x} \\
&= \frac{f(t)(g(t) - g(x)) + g(x)(f(t) - f(x))}{ t -x } \\
&= f(x)g'(x) + g(x) f'(x)
\end{align*}
*** Division
- Reduction method to transform to a form which is similar to the multiplication

\begin{align*}
\frac{f}{g}'(x) &= \lim_{ t \to x } \frac{\frac{f}{g}(t) - \frac{f}{g}(x) }{t - x} = \lim_{ t \to x } \frac{1}{g(t)g(x)} \left( \frac{f(t)g(x)-f(x)g(t)}{t - x} \right) \\
&= \lim_{ t \to x } \frac{1}{g(t)g(x)}\left( \frac{g(x)(f(t) - f(x)) - f(x)(g(t) - g(x))}{t - x} \right) \\
&= \frac{f'(x)g(x) - f(x)g'(x)}{g^{2}(x)}
\end{align*}

* Chain rule

[!important]
This is the most important rule in calculation of differentiation.
*Theorem* For function \(f, g\), if \(f\) is differentiable at \(x\), and \(g\) is differentiable at \(f(x)\) then for \(h := g \circ f\).
\[h'(x) = g'(f(x))f'(x)\]

--------------

* Mean value theorem
- Mean value theorem is a characterisation of the continuity of a function and its derivative.

There are three version of it
*Lemma* Let \(f\) defines on \((a,b)\) and \(f(c)\) is a local maximum/minimum, then \(f'(c) = 0\)

The derivative is greater than zero approaching from left hand side, and less than zero when approaching from right hand side, then by Sandwich's theorem.

** *The* mean value theorem (Lagrange)
*Theorem* \(f\) are continuous on \([a, b]\) and differentiable on \((a,b)\). Then
\[f(b) - f(a) = (b - a)f'(x)\]
#+begin_quote
Special case of generalised mean value theorem
Let g(x) = x.
#+end_quote

** Generalised mean value theorem (Cauchy)
*Theorem* \(f\) and \(g\) are continuous on \([a,b]\) and differentiable on \((a,b)\). Then
\[ [f(b) - f(a)]g'(x) = [g(b) - g(a)]f'(x)\]
A geometrical interpretation is the mean value theorem for parametric function \(x = g(t), y = f(t)\) on \(XY\)-plane

*** DONE Motivation of Cauchy MVT
CLOSED: [2024-07-20 Sat 14:45]
It generalises the mean value theorem to parametric functions.

** The continuity of derivatives
*** DONE The intermediate value theorem for derivative
CLOSED: [2024-07-20 Sat 15:30]
Portrays the connectedness and continuity of derivative

#+begin_quote
The difficulty of this theorem is we couldn't know the continuity of the derivative of the function (second-kind discontinuity).
#+end_quote

*Theorem* Suppose \( f \) is a real differentaible function on \( [a,b] \) and suppose \( f'(a) < \lambda < f'(b) \) (or >). Then there is a point \( x \in (a,b) \) such that \( f'(x) = \lambda \).

#+begin_quote Idea
Integrate it into \( f \) such that we could apply mean value theorem, because we know that \( f \) is continuous.
#+end_quote

** L'Hospital's Rule
*Theorem* Suppose \(g'(x) \ne 0\). If
\[f(x) \to 0 \text{ and } g(x) \to 0 \text{ as } x \to a\]
or if
\[g(x) \to \infty \text{ as } x \to a\]
then \[\frac{f(x)}{g(x)} = \frac{f'(x)}{g'(x)} \text{ as } x \to a.\]
*** Idea
Use Cauchy mean value theorem to approach a upper bound and a lower bound of \(\frac{f(x)}{g(x)}\) and then use sandwich.

* Taylor's theorem
#+begin_quote
Polynomial approximation of function
#+end_quote

*Theorem* Suppose \(f\) is a real function defined on \([a,b]\) and \(f^{(n-1)}\) is continuous on \([a, b]\), \(f^{(n)}\) exists on \((a,b)\). For two distinct point \(\alpha, \beta \in [a, b]\), define

$$P(t) = \sum_{k=0}^{n-1} \frac{f^{(k)}(a)}{k!} (t-a)^{k}$$

Then there exists \(x \in (\alpha, \beta )\) such that

#+begin_quote
This is a consequence of mean value theorem. Note that for n = 1, this is just the mean value theorem.
#+end_quote

1. Determine the errors from the polynomial to the function.
2. Then show that this error is negligible

* Vector-valued functions

Basically the same as dealing with 2-dimensional by letting \(\varepsilon\) be \( \sqrt[n]{\varepsilon} \). The continuity will remains according to the norm.
But mean value theorem will become weaker on n-dimensional, since the graph of \( f \) now has more path from one point to another point. That, we could find a point \( x \in (a, b) \) such that the relation becoming no longer an equal
\[
\mathbf{f}(b) - \mathbf{f}(a) \le (b - a) \left| \mathbf{f}' (x) \right|\]


* DONE My first post :tag1:@category1:
:PROPERTIES:
:EXPORT_FILE_NAME: my-first-post
:END:
This is my post body
